export default [
  {
    checked: false,
    childMenu: [
      {
        checked: false,
        childMenu: [],
        deleted: 0,
        menuApp: "",
        menuCode: "workOrderAccept",
        menuTitle: "工单接收",
        menuIcon: "",
        menuId: 38,
        menuLevel: 2,
        menuName: "工单接收",
        menuSort: 21,
        menuWap: "",
        parentMenuId: 37,
        menuUrl: "/pages/views/workOrderAccept/index",
        icon: 2
      },
      {
        checked: false,
        childMenu: [],
        deleted: 0,
        menuApp: "",
        menuCode: "workOrderDevide",
        menuTitle: "工单工序分配",
        menuIcon: "",
        menuId: 37,
        menuLevel: 2,
        menuName: "工单工序分配",
        menuSort: 20,
        menuWap: "",
        parentMenuId: 37,
        menuUrl: "/pages/views/workOrderDevide/index",
        icon: 3
      },
    ],
    deleted: 0,
    menuApp: "",
    menuCode: "check",
    menuTitle: "lang.ot.app.check",
    menuIcon: "",
    menuId: 1,
    menuLevel: 1,
    menuName: "工单",
    menuSort: 6,
    menuWap: "",
    parentMenuId: null,
  },
  {
    deleted: 0,
    menuApp: "",
    menuCode: "check",
    menuTitle: "lang.ot.app.check",
    menuIcon: "",
    menuId: 2,
    menuLevel: 1,
    menuName: "生产",
    menuSort: 6,
    menuWap: "",
    parentMenuId: null,
    childMenu: [
      {
        checked: false,
        childMenu: [],
        deleted: 0,
        menuApp: "",
        menuCode: "upDownMachine",
        menuTitle: "上下机",
        menuIcon: "",
        menuId: 36,
        menuLevel: 2,
        menuName: "上下机",
        menuSort: 19,
        menuWap: "",
        parentMenuId: 37,
        menuUrl: "/pages/views/upDownMachine/index",
        icon: 4
      },
      {
        checked: false,
        childMenu: [],
        deleted: 0,
        menuApp: "",
        menuCode: "submission",
        menuTitle: "送检",
        menuIcon: "",
        menuId: 35,
        menuLevel: 2,
        menuName: "送检",
        menuSort: 18,
        menuWap: "",
        parentMenuId: 37,
        menuUrl: "/pages/views/submission/index",
        icon: 5
      },
      {
        checked: false,
        childMenu: [],
        deleted: 0,
        menuApp: "",
        menuCode: "check",
        menuTitle: "lang.ot.app.check",
        menuIcon: "",
        menuId: 39,
        menuLevel: 2,
        menuName: "点检",
        menuSort: 22,
        menuWap: "",
        parentMenuId: 37,
        menuUrl: "/pages/views/spotCheck/spotCheckList",
        icon: 1
      },
    ],
    checked: false,
  },
  {
    deleted: 0,
    menuApp: "",
    menuCode: "check",
    menuTitle: "lang.ot.app.check",
    menuIcon: "",
    menuId: 3,
    menuLevel: 1,
    menuName: "质量",
    menuSort: 6,
    menuWap: "",
    parentMenuId: null,
    childMenu: [
      {
        checked: false,
        childMenu: [],
        deleted: 0,
        menuApp: "",
        menuCode: "checkList",
        menuTitle: "待检测清单",
        menuIcon: "",
        menuId: 34,
        menuLevel: 2,
        menuName: "待检测清单",
        menuSort: 17,
        menuWap: "",
        parentMenuId: 37,
        menuUrl: "/pages/views/checkList/index",
        icon: 6
      },
      {
        checked: false,
        childMenu: [],
        deleted: 0,
        menuApp: "",
        menuCode: "checkedList",
        menuTitle: "检测记录",
        menuIcon: "",
        menuId: 33,
        menuLevel: 2,
        menuName: "检测记录",
        menuSort: 16,
        menuWap: "",
        parentMenuId: 37,
        menuUrl: "/pages/views/checkedList/index",
        icon: 7
      },
      {
        checked: false,
        childMenu: [],
        deleted: 0,
        menuApp: "",
        menuCode: "ngList",
        menuTitle: "不良清单",
        menuIcon: "",
        menuId: 32,
        menuLevel: 2,
        menuName: "不良清单",
        menuSort: 15,
        menuWap: "",
        parentMenuId: 37,
        menuUrl: "/pages/views/ngList/index",
        icon: 8
      },
    ],
    checked: false,
  },
  {
    deleted: 0,
    menuApp: "",
    menuCode: "check",
    menuTitle: "lang.ot.app.check",
    menuIcon: "",
    menuId: 4,
    menuLevel: 1,
    menuName: "查询",
    menuSort: 6,
    menuWap: "",
    parentMenuId: null,
    childMenu: [],
    checked: false,
  }
]